export const GET_SEARCHED_PRODUCTS = 'GET_SEARCHED_PRODUCTS';
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_BY_CATEGORY = 'GET_BY_CATEGORY';
export const GET_PRODUCTS = 'GET_PRODUCTS';
export const GET_PRODUCT_BY_ID = 'GET_PRODUCT_BY_ID';
