export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_ALL_CATEGORIES = "GET_ALL_CATEGORIES";
export const SET_DETAILS = "SET_DETAILS";
export const DELETE_PRODUCT = "DELETE_PRODUCT";
export const DELETE_CATEGORY = "DELETE_CATEGORY";